### ISSUE TITLE
Weird data sync problem

### ISSUE THREAD

**Issue by ameoba32** [estebanrfp/gun.eco#30]
While I am developing custom app, I faced some weird behavior of data sync. I found it might be related to object property names, like "next".  Because it works with other names.

I was able to modify hello world to demonstrate this. Next program syncs first character but then stops. What can be the reason?

```
<!DOCTYPE html>
<style>html, body, textarea { width: 100%; height: 100%; padding: 0; margin: 0; }</style>
<textarea id="paste" placeholder="paste here!"></textarea>
<script src="https://cdn.jsdelivr.net/npm/gun/gun.js"></script><script>
  gun = Gun(['https://gun-manhattan.herokuapp.com/gun']);
  copy = gun.get('test').get('paste947');
  paste.oninput = () => { copy.put({serving:paste.value, next:'test'}) };
  copy.on((data) => { paste.value = data.serving });
</script>
```

Thanks.

**Comment by estebanrfp** [comment]
this is the official repository of the documentation platform, the problem you report seems to be directly related to Gun. https://github.com/amark/gun
